After latest changes in POM I was not able run tests, had same problem as discussed here: https://stackoverflow.com/questions/57040675/java-lang-noclassdeffounderror-org-junit-platform-commons-preconditionviolation